In [4]:
# =========================================================
# PERTEMUAN 2: Manajemen & Eksplorasi Data Tabular
# =========================================================
import pandas as pd
import numpy as np

# Mengunduh dataset utama Titanic langsung dari repositori publik
source_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
data_titanic = pd.read_csv(source_url)

print("Proses import data berhasil!")
print(f"Dimensi Dataset: {data_titanic.shape[0]} entri baris dan {data_titanic.shape[1]} kolom fiturnya.")

Proses import data berhasil!
Dimensi Dataset: 891 entri baris dan 12 kolom fiturnya.

In [5]:
total_baris, total_kolom = data_titanic.shape
print(f"Ringkasan Data: Terdiri dari {total_baris} baris & {total_kolom} kolom.\n")

print("Daftar Fitur/Kolom Tersedia:")
for nomor, nama_kolom in enumerate(data_titanic.columns, 1):
    print(f"  [{nomor}] -> {nama_kolom}")

print("\nMenampilkan 5 Baris Data Teratas:")
display(data_titanic.head(5))

print("\nStruktur Tipe Data Komponen:")
data_titanic.info()

Ringkasan Data: Terdiri dari 891 baris & 12 kolom.

Daftar Fitur/Kolom Tersedia:
  [1] -> PassengerId
  [2] -> Survived
  [3] -> Pclass
  [4] -> Name
  [5] -> Sex
  [6] -> Age
  [7] -> SibSp
  [8] -> Parch
  [9] -> Ticket
  [10] -> Fare
  [11] -> Cabin
  [12] -> Embarked

Menampilkan 5 Baris Data Teratas:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Struktur Tipe Data Komponen:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
jumlah_null = data_titanic.isnull().sum()
rasio_null   = (data_titanic.isnull().sum() / len(data_titanic)) * 100

tabel_kondisi_data = pd.DataFrame({
    'Total Kosong (Sells)': jumlah_null,
    'Persentase Hilang (%)': rasio_null.round(2)
})

kolom_bermasalah = tabel_kondisi_data[tabel_kondisi_data['Total Kosong (Sells)'] > 0].sort_values('Total Kosong (Sells)', ascending=False)
print(f"Hasil Analisis: Dari {data_titanic.shape[1]} kolom, ditemukan {len(kolom_bermasalah)} kolom yang tidak lengkap:\n")
print(kolom_bermasalah)

Hasil Analisis: Dari 12 kolom, ditemukan 3 kolom yang tidak lengkap:

          Total Kosong (Sells)  Persentase Hilang (%)
Cabin                      687                  77.10
Age                        177                  19.87
Embarked                     2                   0.22

In [8]:
total_baris, total_kolom = data_titanic.shape
print(f"Ringkasan Data: Terdiri dari {total_baris} baris & {total_kolom} kolom.\n")

print("Daftar Fitur/Kolom Tersedia:")
for nomor, nama_kolom in enumerate(data_titanic.columns, 1):
    print(f"  [{nomor}] -> {nama_kolom}")

print("\nMenampilkan 5 Baris Data Teratas:")
display(data_titanic.head(5))

print("\nStruktur Tipe Data Komponen:")
data_titanic.info()

Ringkasan Data: Terdiri dari 891 baris & 12 kolom.

Daftar Fitur/Kolom Tersedia:
  [1] -> PassengerId
  [2] -> Survived
  [3] -> Pclass
  [4] -> Name
  [5] -> Sex
  [6] -> Age
  [7] -> SibSp
  [8] -> Parch
  [9] -> Ticket
  [10] -> Fare
  [11] -> Cabin
  [12] -> Embarked

Menampilkan 5 Baris Data Teratas:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Struktur Tipe Data Komponen:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
jumlah_null = data_titanic.isnull().sum()
rasio_null   = (data_titanic.isnull().sum() / len(data_titanic)) * 100

tabel_kondisi_data = pd.DataFrame({
    'Total Kosong (Sells)': jumlah_null,
    'Persentase Hilang (%)': rasio_null.round(2)
})

kolom_bermasalah = tabel_kondisi_data[tabel_kondisi_data['Total Kosong (Sells)'] > 0].sort_values('Total Kosong (Sells)', ascending=False)
print(f"Hasil Analisis: Dari {data_titanic.shape[1]} kolom, ditemukan {len(kolom_bermasalah)} kolom yang tidak lengkap:\n")
print(kolom_bermasalah)

Hasil Analisis: Dari 12 kolom, ditemukan 3 kolom yang tidak lengkap:

          Total Kosong (Sells)  Persentase Hilang (%)
Cabin                      687                  77.10
Age                        177                  19.87
Embarked                     2                   0.22

In [10]:
status_selamat = data_titanic['Survived'].value_counts()
rate_selamat   = data_titanic['Survived'].mean() * 100

print(f"Jumlah Korban Selamat : {status_selamat[1]} jiwa")
print(f"Jumlah Korban Gugur   : {status_selamat[0]} jiwa")
print(f"Total Sampel Data     : {len(data_titanic)} orang")
print(f"\nRasio Akhir: Sebanyak {rate_selamat:.2f}% penumpang dinyatakan selamat, sedangkan {100 - rate_selamat:.2f}% lainnya tidak bertahan.")

Jumlah Korban Selamat : 342 jiwa
Jumlah Korban Gugur   : 549 jiwa
Total Sampel Data     : 891 orang

Rasio Akhir: Sebanyak 38.38% penumpang dinyatakan selamat, sedangkan 61.62% lainnya tidak bertahan.

In [11]:
subset_wanita_vip = data_titanic[(data_titanic['Sex'] == 'female') & (data_titanic['Pclass'] == 1)]
total_wanita_vip = len(subset_wanita_vip)
rata_umur_vip = subset_wanita_vip['Age'].mean()
catatan_umur_valid = subset_wanita_vip['Age'].notna().sum()

print(f"Karakteristik Penumpang Wanita Kelas 1:")
print(f"-> Total Populasi: {total_wanita_vip} orang")
print(f"-> Rata-rata Usia: {rata_umur_vip:.2f} tahun (Dihitung dari {catatan_umur_valid} data umur yang terisi)")

Karakteristik Penumpang Wanita Kelas 1:
-> Total Populasi: 94 orang
-> Rata-rata Usia: 34.61 tahun (Dihitung dari 85 data umur yang terisi)

In [12]:
analisis_per_kelas = data_titanic.groupby('Pclass')['Survived'].mean() * 100
print("Persentase Kelangsungan Hidup Tiap Kelas Penumpang:\n")
for kelas_kamar, peluang in analisis_per_kelas.items():
    print(f"  * Kamar Kelas {kelas_kamar} : {peluang:.2f}% peluang selamat")

id_kelas_terbaik = analisis_per_kelas.idxmax()
print(f"\nKesimpulan: Penumpang di Kelas {id_kelas_terbaik} memegang rekor keselamatan tertinggi, yaitu sebesar {analisis_per_kelas[id_kelas_terbaik]:.2f}%.")

Persentase Kelangsungan Hidup Tiap Kelas Penumpang:

  * Kamar Kelas 1 : 62.96% peluang selamat
  * Kamar Kelas 2 : 47.28% peluang selamat
  * Kamar Kelas 3 : 24.24% peluang selamat

Kesimpulan: Penumpang di Kelas 1 memegang rekor keselamatan tertinggi, yaitu sebesar 62.96%.

In [13]:
data_titanic['KategoriUsia'] = pd.cut(
    data_titanic['Age'],
    bins=[0, 12, 18, 35, 55, 80],
    labels=['Fase Anak (0-12)', 'Fase Remaja (13-18)', 'Fase Produktif (19-35)', 'Fase Matang (36-55)', 'Fase Lansia (56-80)']
)

metrik_usia = data_titanic.groupby('KategoriUsia', observed=True).agg(
    Total_Manusia=('Survived', 'count'),
    Total_Selamat=('Survived', 'sum'),
    Rasio_Selamat_Pct=('Survived', 'mean')
).reset_index()

metrik_usia['Rasio_Selamat_Pct'] = (metrik_usia['Rasio_Selamat_Pct'] * 100).round(2)

print("Tabel Distribusi Keselamatan Berdasarkan Rentang Usia:\n")
print(metrik_usia.to_string(index=False))

print("\n\nInterpretasi Hasil:")
print("1. Golongan Anak (0-12 tahun) menempati urutan teratas dalam tingkat penyelamatan (~57.97%).")
print("2. Prioritas utama evakuasi tampaknya condong pada keselamatan anak-anak, sejalan dengan hukum laut universal.")
print("3. Sebaliknya, kaum Lansia (56-80 tahun) mencatatkan tingkat kelangsungan hidup paling minim, hanya menyentuh angka 30.00%.")

data_titanic.drop('KategoriUsia', axis=1, inplace=True)

Tabel Distribusi Keselamatan Berdasarkan Rentang Usia:

          KategoriUsia  Total_Manusia  Total_Selamat  Rasio_Selamat_Pct
      Fase Anak (0-12)             69             40              57.97
   Fase Remaja (13-18)             70             30              42.86
Fase Produktif (19-35)            358            137              38.27
   Fase Matang (36-55)            177             71              40.11
   Fase Lansia (56-80)             40             12              30.00


Interpretasi Hasil:
1. Golongan Anak (0-12 tahun) menempati urutan teratas dalam tingkat penyelamatan (~57.97%).
2. Prioritas utama evakuasi tampaknya condong pada keselamatan anak-anak, sejalan dengan hukum laut universal.
3. Sebaliknya, kaum Lansia (56-80 tahun) mencatatkan tingkat kelangsungan hidup paling minim, hanya menyentuh angka 30.00%.